models/de_new_york/briefcase_money.mdl
models/de_new_york/bulb2.mdl
models/de_new_york/car_police03.mdl
models/de_new_york/fan1.mdl
models/de_new_york/fire_hydrant.mdl
models/de_new_york/Fonapb.mdl
models/de_new_york/golf.mdl
models/de_new_york/NEWyeartree1.mdl
models/de_new_york/paris_bar.mdl
models/de_new_york/phone_pay-US.mdl
models/de_new_york/present1.mdl
models/de_new_york/re_deadguy_2.mdl
models/de_new_york/re_dirt.mdl
models/de_new_york/rubble02.mdl
models/de_new_york/swat_van_nypd.mdl
models/de_new_york/taxi.mdl
models/de_new_york/tree.mdl
models/de_new_york/van1_1.mdl
overviews/de_newyork.txt
overviews/de_newyork.bmp
sound/ambience/FireMax.wav
sound/de_newyork/a1_citytraffic.wav
sound/de_newyork/city01.wav
sound/de_newyork/jinglebells.wav
sound/de_newyork/wind_ambience8.wav
sound/spay/electro01.wav
sprites/flame.spr